### ISSUE TITLE
Add support for CocoaPods

### ISSUE THREAD

**Issue by sirnacnud** [danielinoa/DIImageView#7]
Would it be possible to support installing with CocoaPods?

**Comment by danielinoa** [comment]
It is possible. However, I don't think it makes much sense to provide CocoaPods support for such a small (1 file) dependency. I find it's easier and more manageable to simply drop the `DIImageView.swift` file in the project.

If you think having a `pod` for this would really help you, then I'd be happy to make a `pod` for it.

**Comment by sirnacnud** [comment]
For my projects I prefer to use one tool for dependency management of both the source and project integration. While it is trivial to integrate the single swift file in to the project, I would still have to include it either checked in to my source or as a submodule.

It is not uncommon for a pod to be a single swift file, I am using other pods at the moment which are just that. I would certainly appreciate CocoaPods support and I'm sure other developers would too.

**Comment by danielinoa** [comment]
You got it. I'll make a `pod` soon.

**Comment by danielinoa** [comment]
Support for CocoaPods has been added.
